### ISSUE TITLE
make test: fsa_test_py (Failed)

### ISSUE THREAD

**Issue by Honghe** [k2-fsa/k2#351]
# Environment:
- Ubuntu 20.04.1
- Miniconda3
- PyTorch  1.7.0  py3.8_cuda10.1.243_cudnn7.6.3_0
- k2 4c3c2a9

Error message:
```
The following tests FAILED:
	 34 - fsa_test_py (Failed)
	 43 - union_test_py (Failed)
```
The detailed `make` and `make test`:
```
(torch1.7_cuda10.1) $:~/k2/build$ cmake ..
-- The CUDA compiler identification is NVIDIA 10.1.243
-- The CXX compiler identification is GNU 8.4.0
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No CMAKE_BUILD_TYPE given, default to Debug
-- C++ Standard version: 14
CMake Warning at CMakeLists.txt:88 (message):
  arch 62/72 are not supported for now


-- Downloading pybind11
-- pybind11 is downloaded to /home/ubuntu/k2/build/_deps/pybind11-src
-- Found PythonInterp: /home/ubuntu/miniconda3/envs/torch1.7_cuda10.1/bin/python3.8 (found version "3.8.5") 
-- Found PythonLibs: /home/ubuntu/miniconda3/envs/torch1.7_cuda10.1/lib/libpython3.8.so
-- pybind11 v2.5.0
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr (found version "10.1") 
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: /usr/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr
-- Caffe2: Header version is: 10.1
-- Found CUDNN: /usr/lib/x86_64-linux-gnu/libcudnn.so  
-- Found cuDNN: v7.6.5  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Autodetected CUDA architecture(s):  7.5 7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
-- Found Torch: /home/ubuntu/miniconda3/envs/torch1.7_cuda10.1/lib/python3.8/site-packages/torch/lib/libtorch.so  
-- Downloading cub
-- cub is downloaded to /home/ubuntu/k2/build/_deps/cub-src
-- Downloading moderngpu
-- moderngpu is downloaded to /home/ubuntu/k2/build/_deps/moderngpu-src
-- Downloading googletest
-- googletest is downloaded to /home/ubuntu/k2/build/_deps/googletest-src
-- googletest's binary dir is /home/ubuntu/k2/build/_deps/googletest-build
-- The C compiler identification is GNU 8.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Failed
-- LTO disabled (not supported by the compiler and/or linker)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/k2/build
(torch1.7_cuda10.1) $:~/k2/build$ 
(torch1.7_cuda10.1) $:~/k2/build$ make -j10
Scanning dependencies of target fsa
Scanning dependencies of target gtest
[  1%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/determinize.cc.o
[  1%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/aux_labels.cc.o
[  2%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/arcsort.cc.o
[  2%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/fsa_equivalent.cc.o
[  3%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/fsa_renderer.cc.o
[  4%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/fsa_util.cc.o
[  5%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/connect.cc.o
[  6%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/fsa.cc.o
[  7%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/intersect.cc.o
[  7%] Building CXX object _deps/googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  7%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/properties.cc.o
[  8%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/rmepsilon.cc.o
[  9%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/topsort.cc.o
[  9%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/util.cc.o
[ 10%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/weights.cc.o
[ 11%] Linking CXX shared library ../../../lib/libk2fsa.so
[ 11%] Built target fsa
Scanning dependencies of target context
Scanning dependencies of target _k2host
[ 12%] Building CXX object k2/python/host/csrc/CMakeFiles/_k2host.dir/fsa_equivalent.cc.o
[ 13%] Building CXX object k2/python/host/csrc/CMakeFiles/_k2host.dir/aux_labels.cc.o
[ 13%] Building CXX object k2/python/host/csrc/CMakeFiles/_k2host.dir/fsa.cc.o
[ 13%] Building CXX object k2/python/host/csrc/CMakeFiles/_k2host.dir/fsa_util.cc.o
[ 14%] Building CXX object k2/python/host/csrc/CMakeFiles/_k2host.dir/k2.cc.o
[ 15%] Building CXX object k2/python/host/csrc/CMakeFiles/_k2host.dir/array.cc.o
[ 16%] Building CXX object k2/python/host/csrc/CMakeFiles/_k2host.dir/fsa_algo.cc.o
[ 17%] Building CXX object k2/python/host/csrc/CMakeFiles/_k2host.dir/properties.cc.o
[ 18%] Building CUDA object k2/csrc/CMakeFiles/context.dir/algorithms.cu.o
[ 19%] Linking CXX shared library ../../../lib/libgtestd.so
[ 19%] Built target gtest
[ 19%] Building CUDA object k2/csrc/CMakeFiles/context.dir/array_ops.cu.o
[ 20%] Building CUDA object k2/csrc/CMakeFiles/context.dir/intersect.cu.o
[ 20%] Building CXX object k2/python/host/csrc/CMakeFiles/_k2host.dir/tensor.cc.o
[ 21%] Building CXX object k2/python/host/csrc/CMakeFiles/_k2host.dir/weights.cc.o
Scanning dependencies of target gtest_main
[ 22%] Building CXX object _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 23%] Building CUDA object k2/csrc/CMakeFiles/context.dir/top_sort.cu.o
[ 24%] Building CUDA object k2/csrc/CMakeFiles/context.dir/context.cu.o
[ 24%] Building CUDA object k2/csrc/CMakeFiles/context.dir/dtype.cu.o
[ 25%] Linking CXX shared library ../../../lib/libgtest_maind.so
[ 25%] Built target gtest_main
[ 26%] Building CUDA object k2/csrc/CMakeFiles/context.dir/fsa.cu.o
Scanning dependencies of target weights_test
[ 27%] Building CXX object k2/csrc/host/CMakeFiles/weights_test.dir/weights_test.cc.o
Scanning dependencies of target determinize_test
[ 28%] Building CXX object k2/csrc/host/CMakeFiles/determinize_test.dir/determinize_test.cc.o
[ 29%] Linking CXX executable ../../../bin/weights_test
[ 30%] Linking CXX shared module ../../../../lib/_k2host.cpython-38-x86_64-linux-gnu.so
[ 30%] Built target weights_test
Scanning dependencies of target fsa_equivalent_test
[ 31%] Building CXX object k2/csrc/host/CMakeFiles/fsa_equivalent_test.dir/fsa_equivalent_test.cc.o
[ 32%] Linking CXX executable ../../../bin/determinize_test
[ 32%] Built target determinize_test
Scanning dependencies of target arcsort_test
[ 34%] Building CXX object k2/csrc/host/CMakeFiles/arcsort_test.dir/arcsort_test.cc.o
[ 35%] Building CUDA object k2/csrc/CMakeFiles/context.dir/fsa_algo.cu.o
[ 35%] Built target _k2host
Scanning dependencies of target topsort_test
[ 35%] Building CXX object k2/csrc/host/CMakeFiles/topsort_test.dir/topsort_test.cc.o
[ 35%] Building CUDA object k2/csrc/CMakeFiles/context.dir/fsa_utils.cu.o
[ 35%] Linking CXX executable ../../../bin/fsa_equivalent_test
[ 35%] Built target fsa_equivalent_test
Scanning dependencies of target array_test
[ 35%] Linking CXX executable ../../../bin/arcsort_test
[ 36%] Building CXX object k2/csrc/host/CMakeFiles/array_test.dir/array_test.cc.o
[ 36%] Built target arcsort_test
Scanning dependencies of target intersect_test
[ 36%] Building CXX object k2/csrc/host/CMakeFiles/intersect_test.dir/intersect_test.cc.o
[ 37%] Linking CXX executable ../../../bin/topsort_test
[ 37%] Built target topsort_test
[ 38%] Building CUDA object k2/csrc/CMakeFiles/context.dir/host_shim.cu.o
[ 39%] Linking CXX executable ../../../bin/array_test
[ 40%] Linking CXX executable ../../../bin/intersect_test
[ 40%] Built target array_test
Scanning dependencies of target rmepsilon_test
[ 40%] Building CXX object k2/csrc/host/CMakeFiles/rmepsilon_test.dir/rmepsilon_test.cc.o
[ 40%] Built target intersect_test
Scanning dependencies of target aux_labels_test
[ 41%] Building CXX object k2/csrc/host/CMakeFiles/aux_labels_test.dir/aux_labels_test.cc.o
[ 42%] Linking CXX executable ../../../bin/rmepsilon_test
[ 42%] Built target rmepsilon_test
Scanning dependencies of target properties_test
[ 43%] Building CXX object k2/csrc/host/CMakeFiles/properties_test.dir/properties_test.cc.o
[ 43%] Linking CXX executable ../../../bin/aux_labels_test
[ 43%] Built target aux_labels_test
[ 44%] Building CUDA object k2/csrc/CMakeFiles/context.dir/math.cu.o
[ 45%] Linking CXX executable ../../../bin/properties_test
[ 45%] Built target properties_test
[ 46%] Building CUDA object k2/csrc/CMakeFiles/context.dir/moderngpu_allocator.cu.o
Scanning dependencies of target connect_test
[ 47%] Building CXX object k2/csrc/host/CMakeFiles/connect_test.dir/connect_test.cc.o
[ 47%] Building CUDA object k2/csrc/CMakeFiles/context.dir/ragged.cu.o
Scanning dependencies of target fsa_renderer_test
[ 48%] Building CXX object k2/csrc/host/CMakeFiles/fsa_renderer_test.dir/fsa_renderer_test.cc.o
[ 49%] Linking CXX executable ../../../bin/fsa_renderer_test
[ 50%] Linking CXX executable ../../../bin/connect_test
[ 50%] Built target fsa_renderer_test
Scanning dependencies of target fsa_test
[ 51%] Building CXX object k2/csrc/host/CMakeFiles/fsa_test.dir/fsa_test.cc.o
[ 51%] Built target connect_test
Scanning dependencies of target fsa_util_test
[ 52%] Building CXX object k2/csrc/host/CMakeFiles/fsa_util_test.dir/fsa_util_test.cc.o
[ 52%] Linking CXX executable ../../../bin/fsa_test
[ 52%] Built target fsa_test
[ 53%] Building CUDA object k2/csrc/CMakeFiles/context.dir/ragged_ops.cu.o
[ 54%] Building CUDA object k2/csrc/CMakeFiles/context.dir/tensor.cu.o
[ 55%] Linking CXX executable ../../../bin/fsa_util_test
[ 55%] Built target fsa_util_test
[ 56%] Building CUDA object k2/csrc/CMakeFiles/context.dir/tensor_ops.cu.o
[ 56%] Building CUDA object k2/csrc/CMakeFiles/context.dir/utils.cu.o
[ 57%] Building CUDA object k2/csrc/CMakeFiles/context.dir/pytorch_context.cu.o
[ 58%] Linking CUDA device code CMakeFiles/context.dir/cmake_device_link.o
[ 59%] Linking CUDA shared library ../../lib/libk2context.so
[ 59%] Built target context
Scanning dependencies of target test_utils
Scanning dependencies of target _k2
[ 60%] Building CUDA object k2/csrc/CMakeFiles/test_utils.dir/test_utils.cu.o
[ 60%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/k2.cu.o
[ 61%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch.cu.o
[ 62%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/fsa_algo.cu.o
[ 62%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/ragged.cu.o
[ 62%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/fsa.cu.o
[ 64%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/index_add.cu.o
[ 64%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/arc.cu.o
[ 65%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/torch_util.cu.o
[ 67%] Building CUDA object k2/python/csrc/CMakeFiles/_k2.dir/torch/index_select.cu.o
[ 68%] Linking CUDA shared library ../../lib/libtest_utils.so
[ 68%] Built target test_utils
Scanning dependencies of target cu_utils_test
Scanning dependencies of target cu_fsa_utils_test
[ 69%] Building CUDA object k2/csrc/CMakeFiles/cu_utils_test.dir/utils_test.cu.o
[ 69%] Building CUDA object k2/csrc/CMakeFiles/cu_fsa_utils_test.dir/fsa_utils_test.cu.o
Scanning dependencies of target cu_algorithms_test
[ 69%] Building CUDA object k2/csrc/CMakeFiles/cu_algorithms_test.dir/algorithms_test.cu.o
[ 70%] Linking CUDA device code CMakeFiles/cu_algorithms_test.dir/cmake_device_link.o
[ 71%] Linking CUDA executable ../../bin/cu_algorithms_test
[ 71%] Built target cu_algorithms_test
Scanning dependencies of target cu_array_ops_test
[ 71%] Building CUDA object k2/csrc/CMakeFiles/cu_array_ops_test.dir/array_ops_test.cu.o
[ 72%] Linking CUDA device code CMakeFiles/cu_fsa_utils_test.dir/cmake_device_link.o
[ 73%] Linking CUDA executable ../../bin/cu_fsa_utils_test
[ 73%] Built target cu_fsa_utils_test
Scanning dependencies of target cu_top_sort_test
[ 74%] Building CUDA object k2/csrc/CMakeFiles/cu_top_sort_test.dir/top_sort_test.cu.o
[ 74%] Linking CUDA device code CMakeFiles/cu_top_sort_test.dir/cmake_device_link.o
[ 75%] Linking CUDA executable ../../bin/cu_top_sort_test
[ 75%] Built target cu_top_sort_test
Scanning dependencies of target cu_array_test
[ 76%] Building CUDA object k2/csrc/CMakeFiles/cu_array_test.dir/array_test.cu.o
[ 77%] Linking CUDA device code CMakeFiles/cu_utils_test.dir/cmake_device_link.o
[ 77%] Linking CUDA executable ../../bin/cu_utils_test
[ 77%] Built target cu_utils_test
Scanning dependencies of target cu_fsa_algo_test
[ 78%] Building CUDA object k2/csrc/CMakeFiles/cu_fsa_algo_test.dir/fsa_algo_test.cu.o
[ 78%] Linking CUDA device code CMakeFiles/cu_array_test.dir/cmake_device_link.o
[ 79%] Linking CUDA executable ../../bin/cu_array_test
[ 79%] Built target cu_array_test
Scanning dependencies of target cu_fsa_test
[ 80%] Building CUDA object k2/csrc/CMakeFiles/cu_fsa_test.dir/fsa_test.cu.o
[ 81%] Linking CUDA device code CMakeFiles/cu_fsa_algo_test.dir/cmake_device_link.o
[ 81%] Linking CUDA executable ../../bin/cu_fsa_algo_test
[ 81%] Built target cu_fsa_algo_test
Scanning dependencies of target cu_tensor_test
[ 82%] Building CUDA object k2/csrc/CMakeFiles/cu_tensor_test.dir/tensor_test.cu.o
[ 82%] Linking CUDA device code CMakeFiles/cu_tensor_test.dir/cmake_device_link.o
[ 83%] Linking CUDA executable ../../bin/cu_tensor_test
[ 83%] Built target cu_tensor_test
Scanning dependencies of target cu_ragged_test
[ 83%] Building CUDA object k2/csrc/CMakeFiles/cu_ragged_test.dir/ragged_test.cu.o
[ 84%] Linking CUDA device code CMakeFiles/cu_fsa_test.dir/cmake_device_link.o
[ 85%] Linking CUDA executable ../../bin/cu_fsa_test
[ 85%] Built target cu_fsa_test
Scanning dependencies of target cu_host_shim_test
[ 86%] Building CUDA object k2/csrc/CMakeFiles/cu_host_shim_test.dir/host_shim_test.cu.o
[ 86%] Linking CUDA device code CMakeFiles/cu_host_shim_test.dir/cmake_device_link.o
[ 87%] Linking CUDA executable ../../bin/cu_host_shim_test
[ 87%] Built target cu_host_shim_test
Scanning dependencies of target cu_intersect_test
[ 88%] Building CUDA object k2/csrc/CMakeFiles/cu_intersect_test.dir/intersect_test.cu.o
[ 89%] Linking CUDA device code CMakeFiles/cu_array_ops_test.dir/cmake_device_link.o
[ 90%] Linking CUDA executable ../../bin/cu_array_ops_test
[ 90%] Built target cu_array_ops_test
Scanning dependencies of target cu_log_test
[ 91%] Building CUDA object k2/csrc/CMakeFiles/cu_log_test.dir/log_test.cu.o
[ 91%] Linking CUDA device code CMakeFiles/cu_intersect_test.dir/cmake_device_link.o
[ 92%] Linking CUDA executable ../../bin/cu_intersect_test
[ 92%] Built target cu_intersect_test
Scanning dependencies of target cu_ragged_shape_test
[ 93%] Building CUDA object k2/csrc/CMakeFiles/cu_ragged_shape_test.dir/ragged_shape_test.cu.o
[ 94%] Linking CUDA device code CMakeFiles/cu_log_test.dir/cmake_device_link.o
[ 94%] Linking CUDA executable ../../bin/cu_log_test
[ 94%] Built target cu_log_test
[ 95%] Linking CUDA device code CMakeFiles/cu_ragged_test.dir/cmake_device_link.o
[ 96%] Linking CUDA executable ../../bin/cu_ragged_test
[ 97%] Linking CUDA device code CMakeFiles/cu_ragged_shape_test.dir/cmake_device_link.o
[ 98%] Linking CUDA executable ../../bin/cu_ragged_shape_test
[ 98%] Built target cu_ragged_test
[ 98%] Built target cu_ragged_shape_test
[100%] Linking CUDA shared module ../../../lib/_k2.cpython-38-x86_64-linux-gnu.so
[100%] Built target _k2
(torch1.7_cuda10.1) $:~/k2/build$ make test -j10
Running tests...
Test project /home/ubuntu/k2/build
      Start  1: Test.Cuda.cu_algorithms_test
 1/55 Test  #1: Test.Cuda.cu_algorithms_test .....   Passed    2.18 sec
      Start  2: Test.Cuda.cu_array_ops_test
 2/55 Test  #2: Test.Cuda.cu_array_ops_test ......   Passed    4.61 sec
      Start  3: Test.Cuda.cu_array_test
 3/55 Test  #3: Test.Cuda.cu_array_test ..........   Passed    2.15 sec
      Start  4: Test.Cuda.cu_fsa_algo_test
 4/55 Test  #4: Test.Cuda.cu_fsa_algo_test .......   Passed    2.15 sec
      Start  5: Test.Cuda.cu_fsa_test
 5/55 Test  #5: Test.Cuda.cu_fsa_test ............   Passed    2.13 sec
      Start  6: Test.Cuda.cu_fsa_utils_test
 6/55 Test  #6: Test.Cuda.cu_fsa_utils_test ......   Passed    2.63 sec
      Start  7: Test.Cuda.cu_host_shim_test
 7/55 Test  #7: Test.Cuda.cu_host_shim_test ......   Passed    2.12 sec
      Start  8: Test.Cuda.cu_intersect_test
 8/55 Test  #8: Test.Cuda.cu_intersect_test ......   Passed    2.23 sec
      Start  9: Test.Cuda.cu_log_test
 9/55 Test  #9: Test.Cuda.cu_log_test ............   Passed    4.21 sec
      Start 10: Test.Cuda.cu_ragged_shape_test
10/55 Test #10: Test.Cuda.cu_ragged_shape_test ...   Passed    2.10 sec
      Start 11: Test.Cuda.cu_ragged_test
11/55 Test #11: Test.Cuda.cu_ragged_test .........   Passed    4.40 sec
      Start 12: Test.Cuda.cu_tensor_test
12/55 Test #12: Test.Cuda.cu_tensor_test .........   Passed    0.15 sec
      Start 13: Test.Cuda.cu_top_sort_test
13/55 Test #13: Test.Cuda.cu_top_sort_test .......   Passed    6.51 sec
      Start 14: Test.Cuda.cu_utils_test
14/55 Test #14: Test.Cuda.cu_utils_test ..........   Passed    2.14 sec
      Start 15: Test.arcsort_test
15/55 Test #15: Test.arcsort_test ................   Passed    0.00 sec
      Start 16: Test.array_test
16/55 Test #16: Test.array_test ..................   Passed    0.00 sec
      Start 17: Test.aux_labels_test
17/55 Test #17: Test.aux_labels_test .............   Passed    0.00 sec
      Start 18: Test.connect_test
18/55 Test #18: Test.connect_test ................   Passed    0.01 sec
      Start 19: Test.determinize_test
19/55 Test #19: Test.determinize_test ............   Passed    0.02 sec
      Start 20: Test.fsa_equivalent_test
20/55 Test #20: Test.fsa_equivalent_test .........   Passed    0.03 sec
      Start 21: Test.fsa_renderer_test
21/55 Test #21: Test.fsa_renderer_test ...........   Passed    0.00 sec
      Start 22: Test.fsa_test
22/55 Test #22: Test.fsa_test ....................   Passed    0.00 sec
      Start 23: Test.fsa_util_test
23/55 Test #23: Test.fsa_util_test ...............   Passed    0.01 sec
      Start 24: Test.intersect_test
24/55 Test #24: Test.intersect_test ..............   Passed    0.00 sec
      Start 25: Test.properties_test
25/55 Test #25: Test.properties_test .............   Passed    0.00 sec
      Start 26: Test.rmepsilon_test
26/55 Test #26: Test.rmepsilon_test ..............   Passed    0.01 sec
      Start 27: Test.topsort_test
27/55 Test #27: Test.topsort_test ................   Passed    0.00 sec
      Start 28: Test.weights_test
28/55 Test #28: Test.weights_test ................   Passed    0.00 sec
      Start 29: add_epsilon_self_loops_test_py
29/55 Test #29: add_epsilon_self_loops_test_py ...   Passed    2.51 sec
      Start 30: arc_sort_test_py
30/55 Test #30: arc_sort_test_py .................   Passed    2.53 sec
      Start 31: get_tot_scores_test_py
31/55 Test #31: get_tot_scores_test_py ...........   Passed    2.52 sec
      Start 32: connect_test_py
32/55 Test #32: connect_test_py ..................   Passed    2.52 sec
      Start 33: dense_fsa_vec_test_py
33/55 Test #33: dense_fsa_vec_test_py ............   Passed    2.51 sec
      Start 34: fsa_test_py
34/55 Test #34: fsa_test_py ......................***Failed    2.51 sec
      Start 35: index_test_py
35/55 Test #35: index_test_py ....................   Passed    2.47 sec
      Start 36: index_add_test_py
36/55 Test #36: index_add_test_py ................   Passed    2.49 sec
      Start 37: index_select_test_py
37/55 Test #37: index_select_test_py .............   Passed    2.48 sec
      Start 38: intersect_dense_pruned_test_py
38/55 Test #38: intersect_dense_pruned_test_py ...   Passed    2.49 sec
      Start 39: intersect_test_py
39/55 Test #39: intersect_test_py ................   Passed    2.48 sec
      Start 40: linear_fsa_test_py
40/55 Test #40: linear_fsa_test_py ...............   Passed    2.46 sec
      Start 41: shortest_path_test_py
41/55 Test #41: shortest_path_test_py ............   Passed    2.48 sec
      Start 42: top_sort_test_py
42/55 Test #42: top_sort_test_py .................   Passed    2.47 sec
      Start 43: union_test_py
43/55 Test #43: union_test_py ....................***Failed    2.46 sec
      Start 44: host_arcsort_test_py
44/55 Test #44: host_arcsort_test_py .............   Passed    0.49 sec
      Start 45: host_array_test_py
45/55 Test #45: host_array_test_py ...............   Passed    0.46 sec
      Start 46: host_aux_labels_test_py
46/55 Test #46: host_aux_labels_test_py ..........   Passed    0.47 sec
      Start 47: host_connect_test_py
47/55 Test #47: host_connect_test_py .............   Passed    0.47 sec
      Start 48: host_determinize_test_py
48/55 Test #48: host_determinize_test_py .........   Passed    0.48 sec
      Start 49: host_fsa_equivalent_test_py
49/55 Test #49: host_fsa_equivalent_test_py ......   Passed    0.50 sec
      Start 50: host_fsa_test_py
50/55 Test #50: host_fsa_test_py .................   Passed    0.46 sec
      Start 51: host_intersect_test_py
51/55 Test #51: host_intersect_test_py ...........   Passed    0.46 sec
      Start 52: host_properties_test_py
52/55 Test #52: host_properties_test_py ..........   Passed    0.47 sec
      Start 53: host_rmepsilon_test_py
53/55 Test #53: host_rmepsilon_test_py ...........   Passed    0.48 sec
      Start 54: host_topsort_test_py
54/55 Test #54: host_topsort_test_py .............   Passed    0.47 sec
      Start 55: host_weights_test_py
55/55 Test #55: host_weights_test_py .............   Passed    0.46 sec

96% tests passed, 2 tests failed out of 55

Total Test time (real) =  82.90 sec

The following tests FAILED:
	 34 - fsa_test_py (Failed)
	 43 - union_test_py (Failed)
Errors while running CTest
make: *** [Makefile:84: test] Error 8
```

**Comment by csukuangfj** [comment]
Thanks for reporting.


Could you please try:

```bash
cd build
export PYTHONPATH=$PWD/../k2/python:$PWD/lib:$PYTHONPATH
python3 ../k2/python/tests/fsa_test.py

python3 ../k2/python/tests/union_test.py
```

What are the outputs of the above commands?

**Comment by danpovey** [comment]
BTW, fsa_test.py always fails for me too; always has.  I assumed the code
was out of date or something.

**Comment by Honghe** [comment]
@csukuangfj the outputs of the commands are as follows:
```
(torch1.7_cuda10.1) $:~/k2/build$ python ../k2/python/tests/fsa_test.py 
.....[ [ 0 1 1 0.1 0 2 2 0.2 ] [ 1 2 3 0.3 ] [ 2 3 -1 0.4 ] [ ] ]
.E....
======================================================================
ERROR: test_symbol_table_and_dot (__main__.TestFsa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/torch1.7_cuda10.1/lib/python3.8/site-packages/graphviz-0.15-py3.8.egg/graphviz/backend.py", line 164, in run
    proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
  File "/home/ubuntu/miniconda3/envs/torch1.7_cuda10.1/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/ubuntu/miniconda3/envs/torch1.7_cuda10.1/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../k2/python/tests/fsa_test.py", line 365, in test_symbol_table_and_dot
    dot.render('/tmp/fsa', format='pdf')
  File "/home/ubuntu/miniconda3/envs/torch1.7_cuda10.1/lib/python3.8/site-packages/graphviz-0.15-py3.8.egg/graphviz/files.py", line 207, in render
    rendered = backend.render(self._engine, format, filepath,
  File "/home/ubuntu/miniconda3/envs/torch1.7_cuda10.1/lib/python3.8/site-packages/graphviz-0.15-py3.8.egg/graphviz/backend.py", line 221, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "/home/ubuntu/miniconda3/envs/torch1.7_cuda10.1/lib/python3.8/site-packages/graphviz-0.15-py3.8.egg/graphviz/backend.py", line 167, in run
    raise ExecutableNotFound(cmd)
graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'fsa'], make sure the Graphviz executables are on your systems' PATH

----------------------------------------------------------------------
Ran 11 tests in 1.821s

FAILED (errors=1)
(torch1.7_cuda10.1) $:~/k2/build$ python ../k2/python/tests/union_test.py 
[I] /home/ubuntu/k2/k2/csrc/fsa_algo.cu:Union:620 [ 0 1 0 0 0 4 0 0 0 5 0 0 1 2 1 0.1 1 3 2 0.2 2 3 3 0.3 2 7 -1 0.4 3 7 -1 0.5 3 2 5 0.55 4 7 -1 0.6 5 6 6 0.7 6 5 7 0.8 6 5 8 0.9 6 7 -1 1 ]
[I] /home/ubuntu/k2/k2/csrc/fsa_algo.cu:Union:621 [ 0 0 0 1 1 2 2 3 3 4 5 6 6 6 ]
E
======================================================================
ERROR: test (__main__.TestUnion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/torch1.7_cuda10.1/lib/python3.8/site-packages/graphviz-0.15-py3.8.egg/graphviz/backend.py", line 164, in run
    proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
  File "/home/ubuntu/miniconda3/envs/torch1.7_cuda10.1/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/ubuntu/miniconda3/envs/torch1.7_cuda10.1/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../k2/python/tests/union_test.py", line 49, in test
    dot.render('/tmp/fsa', format='pdf')
  File "/home/ubuntu/miniconda3/envs/torch1.7_cuda10.1/lib/python3.8/site-packages/graphviz-0.15-py3.8.egg/graphviz/files.py", line 207, in render
    rendered = backend.render(self._engine, format, filepath,
  File "/home/ubuntu/miniconda3/envs/torch1.7_cuda10.1/lib/python3.8/site-packages/graphviz-0.15-py3.8.egg/graphviz/backend.py", line 221, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "/home/ubuntu/miniconda3/envs/torch1.7_cuda10.1/lib/python3.8/site-packages/graphviz-0.15-py3.8.egg/graphviz/backend.py", line 167, in run
    raise ExecutableNotFound(cmd)
graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'fsa'], make sure the Graphviz executables are on your systems' PATH

----------------------------------------------------------------------
Ran 1 test in 1.812s

FAILED (errors=1)
```

After installed `graphviz`, all passed:
```
$: python ../k2/python/tests/union_test.py 
[I] /home/ubuntu/k2/k2/csrc/fsa_algo.cu:Union:620 [ 0 1 0 0 0 4 0 0 0 5 0 0 1 2 1 0.1 1 3 2 0.2 2 3 3 0.3 2 7 -1 0.4 3 7 -1 0.5 3 2 5 0.55 4 7 -1 0.6 5 6 6 0.7 6 5 7 0.8 6 5 8 0.9 6 7 -1 1 ]
[I] /home/ubuntu/k2/k2/csrc/fsa_algo.cu:Union:621 [ 0 0 0 1 1 2 2 3 3 4 5 6 6 6 ]
k2.Fsa: 0 1 0 0
0 4 0 0
0 5 0 0
1 2 1 0.1
1 3 2 0.2
2 3 3 0.3
2 7 -1 0.4
3 7 -1 0.5
3 2 5 0.55
4 7 -1 0.6
5 6 6 0.7
6 5 7 0.8
6 5 8 0.9
6 7 -1 1
6
properties_str = "Nonempty|MaybeAccessible|MaybeCoaccessible".
.
----------------------------------------------------------------------
Ran 1 test in 1.829s

OK
(torch1.7_cuda10.1) $:~/k2/build$ python ../k2/python/tests/fsa_test.py 
.....[ [ 0 1 1 0.1 0 2 2 0.2 ] [ 1 2 3 0.3 ] [ 2 3 -1 0.4 ] [ ] ]
......
----------------------------------------------------------------------
Ran 11 tests in 1.828s

OK
```

**Comment by danpovey** [comment]
For me fsa_test.py fails with:
PermissionError: [Errno 13] Permission denied: '/tmp/fsa'

**Comment by qindazhu** [comment]
This is becasue fst_test.py tries to write the output Fsa (dot file) to `/tmp/fsa`, not sure why you have no the permission to do this, it runs successfully in my local (I think we have same permission on the cluster)

**Comment by csukuangfj** [comment]
> BTW, fsa_test.py always fails for me too

Please check that `/tmp` exists and is writable.

**Comment by csukuangfj** [comment]
@Honghe 

Please run
```bash
pip install graphviz
```

or 
```bash
cd k2
pip install -r requirements.txt
```

**Comment by qindazhu** [comment]
RE graphviz, @csukuangfj I think it's better if we can do this automatically when user install k2?

**Comment by danpovey** [comment]
We shouldn't just attempt to write to a specific file in /tmp, we should
use some kind of mktemp.
In my case it fails because there is a file in /tmp/fsa created by Haowen.

**Comment by qindazhu** [comment]
Aha, OK

**Comment by csukuangfj** [comment]
> RE graphviz, @csukuangfj I think it's better if we can do this automatically when user install k2?
> We shouldn't just attempt to write to a specific file in /tmp

Will fix them.

**Comment by csukuangfj** [comment]
> RE graphviz, @csukuangfj I think it's better if we can do this automatically when user install k2?

Yes, `pip install k2` will install `graphviz` automatically. The problem is that users run `ctest` without
installing `k2` and its requirements.

CMake 3.18 is removed in #354 .

**Comment by csukuangfj** [comment]
> We shouldn't just attempt to write to a specific file in /tmp

Fixed in #354

**Comment by csukuangfj** [comment]
Closing as it has been fixed.

**Comment by jtrmal** [comment]
FYI, this issue  still exists, kinda -- even if graphviz python package is installed,  the "real" graphviz's dot (original binaries, not the python wrapper) might be missing. Not sure what can be done with system dependency -- probably make a cmake check?

**Comment by csukuangfj** [comment]
For the system dependency, the user has to run

sudo apt-get install graphviz 

One alternative I think is to check in the test code that if graphviz (not the Python package) is not installed, we just skip the test and print a warning.
